server:
  port: 4041 
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ims_main?currentSchema=ims-user
    username: abhi18
    password: abhi18
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
   

name: bharat
